2603110115

diff --git a/deb--config b/deb--config
--- a/deb--config
+++ b/deb--config
@@ -17,7 +17,7 @@ if [[ $EUID -ne 0 ]]; then
 fi
 
 #-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
-[[ "$DEB_LIB_STATUS" == "loaded" ]] || source <(curl -sL https://mls.sk87.top/deb--lib) || { echo "Library load failed"; exit 1; }
+[["${DEB_LIB_STATUS:-}" == "loaded"]] || source <(curl -sL https://mls.sk87.top/deb--lib) || { echo "Library load failed"; exit 1; }
 #-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
 source /etc/os-release
 RAW_NAME="raw--deb--config"
