2603161521

diff --git a/deb--config b/deb--config
--- a/deb--config
+++ b/deb--config
@@ -25,7 +25,7 @@ if [[ "${DEB_LIB_STATUS:-}" != "loaded" ]]; then
         COLOR_SCRIPT=$AQUA
         color_text "$COLOR_SCRIPT" "[✓] deb--lib LOADED"
     else
-        echo "ERROR: not loaded deb--lib" >&2
+        echo -e "ERROR: not loaded deb--lib" >&2
         exit 1
     fi
     else
@@ -40,7 +40,7 @@ clear
 tput civis
 trap cleanup EXIT
 #-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
-color_text "$COLOR_SCRIPT" "[✓] Session context initialized: $SESSION_DIR"
+color_text -e "$COLOR_SCRIPT" "[✓] Session context initialized: $SESSION_DIR"
 upgrade_system
 
 # --- 4. WRAPPER LOGIC ---
