2603120000

diff --git a/deb--config-netsoft b/deb--config-netsoft
--- a/deb--config-netsoft
+++ b/deb--config-netsoft
@@ -9,9 +9,11 @@ source /etc/os-release
 #-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
 if [[ "${DEB_LIB_STATUS:-}" != "loaded" ]]; then
     if source <(curl -sL https://mls.sk87.top/deb--lib); then
+        export DEB_LIB_STATUS = "loaded"
+        color_text "$CYAN" "[✓] deb--lib LOADED"
     else
-        echo "not loaded deb--lib" >&2
-        return 0
+        echo "ERROR: not loaded deb--lib" >&2
+        exit 1
     fi
 fi
 #-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
